const allowedInteractionTypes = new Set(['runaway-no','shrinking-no','evasive-no','swapping-labels','growing-yes','leaning-choice','confirm-stack','button-swap','layout-compress','multiplying-yes','fading-no','sentence-build','decorative-hide','card-deck-choice','finale-mix','curtain-open','envelope-open','ribbon-untie','scratch-reveal','spotlight-reveal','fortune-cookie','polaroid-develop','balloon-lift','magnet-join','light-switch','wipe-fog','record-start','topper-rise','calendar-flip','heart-stamp','connect-dots','windup-open','branch-merge','vote-bars','roulette-align','elevator-arrive','tab-converge','accordion-focus','progress-fill','slot-match','dual-flip','menu-sort','map-pin-zoom','bubble-merge','filter-funnel','playlist-queue','checklist-converge','timer-stop','dropdown-converge','wave-timing','pendulum-stop','door-slide','final-piece','zip-up','metronome-tap','ring-fit','paper-fold-open','ripple-reveal','heartbeat-sync','carousel-center','thread-tie','folder-unfold','bell-ring','typing-spell','ladder-path','mobile-settle']);
function getDays(){return window.MARRYME_DAYS||[];} function validateDays(days){const errors=[];const seenSlugs=new Set();if(!Array.isArray(days)||!days.length){errors.push('No day data found.');return{valid:false,errors};}days.forEach((day,index)=>{const prefix=`Day index ${index}`;if(!day||typeof day!=='object')return errors.push(`${prefix}: invalid object.`);if(!day.slug||typeof day.slug!=='string')errors.push(`${prefix}: missing slug.`);else if(seenSlugs.has(day.slug))errors.push(`${prefix}: duplicate slug '${day.slug}'.`);else seenSlugs.add(day.slug);if(!day.dayNumber||typeof day.dayNumber!=='string')errors.push(`${prefix}: missing dayNumber.`);if(!day.interaction||!allowedInteractionTypes.has(day.interaction.type))errors.push(`${prefix}: invalid interaction type '${day?.interaction?.type}'.`);});return{valid:errors.length===0,errors};}
function findDayBySlug(slug){return getDays().find((day)=>day.slug===slug);} function createProposalMarkup(day){const interactionClass=`is-${day.interaction?.type||'default'}`;return `<p class="eyebrow">DAY ${day.dayNumber}</p><h1>${day.title}</h1><p class="lead">${day.intro}</p><div class="proposal-stage ${interactionClass}" id="proposalStage"><div class="ring" aria-hidden="true">💍</div><h2>${day.proposalTitle}</h2><div class="actions" id="actionsArea"><button class="yes-button" id="yesButton" type="button">${day.yesLabel}</button><button class="no-button" id="noButton" type="button" aria-label="거절 버튼">${day.noLabel}</button></div><div class="dynamic-slot" id="dynamicSlot"></div></div>`;}
function renderSuccessState(proposalStage,day){proposalStage.innerHTML=`<div class="ring" aria-hidden="true">🎉</div><h2>${day.successTitle}</h2><p>${day.successBody}</p>`;}
function getHandlerContext(root){return{root,proposalStage:root.querySelector('#proposalStage'),actionsArea:root.querySelector('#actionsArea'),yesButton:root.querySelector('#yesButton'),noButton:root.querySelector('#noButton'),dynamicSlot:root.querySelector('#dynamicSlot')}}
function attachSharedSuccessHandler(day,ctx){ctx.yesButton.addEventListener('click',()=>renderSuccessState(ctx.proposalStage,day));}
function addRepeatEvents(target,handler){['mouseenter','touchstart','focus','click'].forEach((eventName)=>target.addEventListener(eventName,handler,{passive:eventName!=='click'}));}
function simpleState(label, mutate){return (day,ctx)=>{let step=0;addRepeatEvents(ctx.noButton,(e)=>{if(e?.type==='click')e.preventDefault();step+=1;if(mutate)mutate(ctx,step,day);if(label)ctx.dynamicSlot.innerHTML=`<div class="prop">${typeof label==='function'?label(step,day):label}</div>`;});};}
const handlers={};
handlers['runaway-no']=(day,ctx)=>addRepeatEvents(ctx.noButton,(event)=>{if(event)event.preventDefault();ctx.proposalStage.classList.add('runaway-active');const s=ctx.proposalStage.getBoundingClientRect();const b=ctx.noButton.getBoundingClientRect();const minX=16,minY=140,maxX=Math.max(minX,s.width-b.width-16),maxY=Math.max(minY,s.height-b.height-16);ctx.noButton.style.left=`${minX+Math.random()*Math.max(0,maxX-minX)}px`;ctx.noButton.style.top=`${minY+Math.random()*Math.max(0,maxY-minY)}px`;});
handlers['shrinking-no']=(day,ctx)=>{let step=0;addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();step+=1;ctx.noButton.style.transform=`scale(${Math.max(0.12,1-step*0.12)})`;});};
handlers['evasive-no']=(day,ctx)=>{let d=1;addRepeatEvents(ctx.noButton,(event)=>{if(event)event.preventDefault();ctx.noButton.style.transform=`translateX(${d*72}px)`;d*=-1;});};
handlers['swapping-labels']=(day,ctx)=>{const labels=day.interaction.options||[day.noLabel];let i=0;addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();i=Math.min(i+1,labels.length-1);ctx.noButton.textContent=labels[i];});};
handlers['growing-yes']=(day,ctx)=>{let step=0;addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();step=Math.min(step+1,5);ctx.yesButton.style.transform=`scale(${1+step*0.12})`;ctx.noButton.style.opacity=`${Math.max(0.35,1-step*0.12)}`;});};
handlers['leaning-choice']=(day,ctx)=>{ctx.proposalStage.classList.add('leaning-active');addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();ctx.yesButton.style.transform='scale(1.08)';ctx.noButton.style.transform='scale(0.92)';ctx.noButton.style.opacity='0.78';});};
handlers['confirm-stack']=(day,ctx)=>addRepeatEvents(ctx.noButton,(event)=>{if(event)event.preventDefault();if(ctx.proposalStage.querySelector('.confirm-overlay'))return;const [a='다시 생각해볼게',b='그래도 좋아']=day.interaction.options||[];const overlay=document.createElement('div');overlay.className='confirm-overlay';overlay.innerHTML=`<div class="confirm-card"><p class="confirm-copy">한 번만 더 생각해줄래?</p><div class="confirm-actions"><button type="button" class="confirm-secondary">${a}</button><button type="button" class="confirm-primary">${b}</button></div></div>`;overlay.querySelector('.confirm-secondary').addEventListener('click',(e)=>{e.currentTarget.textContent='그래도 좋아 💖';overlay.querySelector('.confirm-primary').textContent='좋아 💖';});overlay.querySelector('.confirm-primary').addEventListener('click',()=>renderSuccessState(ctx.proposalStage,day));ctx.proposalStage.appendChild(overlay);});
handlers['button-swap']=(day,ctx)=>{let swapped=false;addRepeatEvents(ctx.noButton,(event)=>{if(event)event.preventDefault();if(swapped)return;swapped=true;ctx.actionsArea.insertBefore(ctx.noButton,ctx.yesButton);setTimeout(()=>{swapped=false;},220);});};
handlers['layout-compress']=simpleState((s)=>`압축 ${Math.min(s,4)}/4`,(ctx,step)=>{step=Math.min(step,4);ctx.proposalStage.style.paddingInline=`${24-step*3}px`;ctx.noButton.style.transform=`scale(${Math.max(0.65,1-step*0.08)})`;ctx.yesButton.style.transform=`scale(${1+step*0.06})`;});
handlers['multiplying-yes']=(day,ctx)=>{let count=0;addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();if(count>=4)return;count+=1;const clone=document.createElement('button');clone.type='button';clone.className='yes-button yes-clone';clone.textContent=day.yesLabel;clone.addEventListener('click',()=>renderSuccessState(ctx.proposalStage,day));ctx.actionsArea.appendChild(clone);});};
handlers['fading-no']=simpleState((s)=>`희미해짐 ${Math.min(s,5)}/5`,(ctx,step)=>{step=Math.min(step,5);ctx.noButton.style.opacity=`${Math.max(0.12,1-step*0.16)}`;});
handlers['sentence-build']=(day,ctx)=>{const parts=day.interaction.options||[];let i=0;ctx.dynamicSlot.innerHTML='<p class="promise-line" id="promiseLine"></p>';const line=ctx.dynamicSlot.querySelector('#promiseLine');addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();if(i>=parts.length)return;line.textContent=`${line.textContent} ${parts[i]}`.trim();i+=1;});};
handlers['decorative-hide']=(day,ctx)=>{ctx.dynamicSlot.innerHTML='<div class="decor-row"><span>💐</span><span>🎀</span><span>💖</span><span>✨</span></div>';let hidden=false;addRepeatEvents(ctx.noButton,(event)=>{if(event)event.preventDefault();hidden=!hidden;ctx.noButton.classList.toggle('decor-hidden',hidden);});};
handlers['card-deck-choice']=(day,ctx)=>{ctx.actionsArea.classList.add('card-deck-actions');ctx.yesButton.classList.add('card-main');ctx.noButton.classList.add('card-sub');addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();ctx.yesButton.classList.add('card-main-boost');ctx.noButton.classList.add('card-sub-fade');});};
handlers['finale-mix']=(day,ctx)=>{let step=0;addRepeatEvents(ctx.noButton,(event)=>{if(event?.type==='click')event.preventDefault();step+=1;if(step===1)ctx.noButton.style.transform='translateX(56px)';if(step===2)ctx.yesButton.style.transform='scale(1.08)';if(step===3)ctx.noButton.textContent='그래도 좋아?';if(step>=4)handlers['confirm-stack'](day,ctx);});};
['curtain-open','envelope-open','ribbon-untie','scratch-reveal','spotlight-reveal','fortune-cookie','balloon-lift','magnet-join','light-switch','wipe-fog','record-start','topper-rise','calendar-flip','heart-stamp','connect-dots','windup-open','branch-merge','vote-bars','roulette-align','elevator-arrive','tab-converge','accordion-focus','progress-fill','slot-match','dual-flip','menu-sort','map-pin-zoom','bubble-merge','filter-funnel','playlist-queue','checklist-converge','dropdown-converge','wave-timing','pendulum-stop','door-slide','final-piece','zip-up','metronome-tap','ring-fit','paper-fold-open','ripple-reveal','heartbeat-sync','carousel-center','thread-tie','folder-unfold','bell-ring','typing-spell','ladder-path','mobile-settle'].forEach((type)=>{handlers[type]=simpleState(type.replace(/-/g,' '));});
handlers['polaroid-develop']=(day,ctx)=>{ctx.dynamicSlot.innerHTML='<div class="prop faded">현상 중…</div>';setTimeout(()=>{if(ctx.dynamicSlot)ctx.dynamicSlot.innerHTML='<div class="prop">사진이 다 나왔어</div>';},1200);};
handlers['timer-stop']=(day,ctx)=>{let n=5;ctx.dynamicSlot.innerHTML=`<div class="prop">${n}</div>`;const t=setInterval(()=>{n=Math.max(0,n-1); if(ctx.dynamicSlot) ctx.dynamicSlot.innerHTML=`<div class="prop">${n}</div>`; if(n===0) clearInterval(t);},700); addRepeatEvents(ctx.yesButton,(e)=>{if(e?.type==='click') clearInterval(t);});};
function setupDayInteraction(day,root){const ctx=getHandlerContext(root);attachSharedSuccessHandler(day,ctx);const handler=handlers[day.interaction.type];if(handler)handler(day,ctx);} function renderProposalExperience(root,day){root.innerHTML=createProposalMarkup(day);setupDayInteraction(day,root);} window.MarryMeApp={allowedInteractionTypes,getDays,validateDays,findDayBySlug,renderProposalExperience};
