window.MARRYME_DAYS = [
  {
    id: 'day-015',
    dayNumber: '015',
    slug: 'day-015',
    title: '오늘의 청혼 페이지',
    subtitle: '지금까지의 장난이 한 번에 몰려오는 피날레.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'finale-mix' },
    tags: ['finale', 'mix', 'day-015']
  },
  {
    id: 'day-014',
    dayNumber: '014',
    slug: 'day-014',
    title: '오늘의 청혼 페이지',
    subtitle: '좋아 쪽 카드만 유독 더 메인처럼 보인다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'card-deck-choice' },
    tags: ['cards', 'deck', 'day-014']
  },
  {
    id: 'day-013',
    dayNumber: '013',
    slug: 'day-013',
    title: '오늘의 청혼 페이지',
    subtitle: '거절 버튼이 장식 사이에 숨어든다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'decorative-hide' },
    tags: ['decor', 'hide', 'day-013']
  },
  {
    id: 'day-012',
    dayNumber: '012',
    slug: 'day-012',
    title: '오늘의 청혼 페이지',
    subtitle: '문장이 천천히 완성된다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: {
      type: 'sentence-build',
      options: ['앞으로', '잘해줄게.', '받아줘서', '고마워.']
    },
    tags: ['sentence', 'promise', 'day-012']
  },
  {
    id: 'day-011',
    dayNumber: '011',
    slug: 'day-011',
    title: '오늘의 청혼 페이지',
    subtitle: '거절 버튼이 점점 희미해진다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'fading-no' },
    tags: ['fade', 'minimal', 'day-011']
  },
  {
    id: 'day-010',
    dayNumber: '010',
    slug: 'day-010',
    title: '오늘의 청혼 페이지',
    subtitle: '좋아 버튼이 하나씩 늘어난다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'multiplying-yes' },
    tags: ['cta', 'duplicate', 'day-010']
  },
  {
    id: 'day-009',
    dayNumber: '009',
    slug: 'day-009',
    title: '오늘의 청혼 페이지',
    subtitle: '화면이 yes 쪽으로 점점 압축된다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'layout-compress' },
    tags: ['layout', 'compress', 'day-009']
  },
  {
    id: 'day-008',
    dayNumber: '008',
    slug: 'day-008',
    title: '오늘의 청혼 페이지',
    subtitle: '버튼이 가까워질 때 슬쩍 자리를 바꾼다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'button-swap' },
    tags: ['swap', 'buttons', 'day-008']
  },
  {
    id: 'day-007',
    dayNumber: '007',
    slug: 'day-007',
    title: '오늘의 청혼 페이지',
    subtitle: '마지막 확인처럼 보여도 결국 마음은 같은 곳으로 간다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: {
      type: 'confirm-stack',
      options: ['다시 생각해볼게', '그래도 좋아']
    },
    tags: ['finale', 'confirm', 'day-007']
  },
  {
    id: 'day-006',
    dayNumber: '006',
    slug: 'day-006',
    title: '오늘의 청혼 페이지',
    subtitle: '화면 전체가 좋아 쪽으로 기울어져 있다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'leaning-choice' },
    tags: ['layout', 'visual-persuasion', 'day-006']
  },
  {
    id: 'day-005',
    dayNumber: '005',
    slug: 'day-005',
    title: '오늘의 청혼 페이지',
    subtitle: '좋아 버튼만 점점 더 눈에 띄게 된다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'growing-yes' },
    tags: ['glow', 'cta', 'day-005']
  },
  {
    id: 'day-004',
    dayNumber: '004',
    slug: 'day-004',
    title: '오늘의 청혼 페이지',
    subtitle: '거절 버튼 문구가 점점 애매해진다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '싫어 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: {
      type: 'swapping-labels',
      options: ['싫어 🙈', '아직…', '조금만 더', '생각해볼게', '좋아할지도?']
    },
    tags: ['copy', 'switch', 'day-004']
  },
  {
    id: 'day-003',
    dayNumber: '003',
    slug: 'day-003',
    title: '오늘의 청혼 페이지',
    subtitle: '거절 버튼이 가까워질수록 옆으로 미끄러진다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'evasive-no' },
    tags: ['movement', 'evasive', 'day-003']
  },
  {
    id: 'day-002',
    dayNumber: '002',
    slug: 'day-002',
    title: '오늘의 청혼 페이지',
    subtitle: '이번엔 거절 버튼이 점점 작아진다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '잠깐만 🙈',
    successTitle: '고마워 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'shrinking-no' },
    tags: ['playful', 'mischief', 'day-002']
  },
  {
    id: 'day-001',
    dayNumber: '001',
    slug: 'day-001',
    title: '오늘의 청혼 페이지',
    subtitle: '거절 버튼은 오늘도 잡히지 않는다.',
    intro: '내 마음을 받아줘 제발~~',
    proposalTitle: '나랑 결혼해줄래?',
    proposalBody: '',
    yesLabel: '좋아 💖',
    noLabel: '싫어 🙈',
    successTitle: '역시 그럴 줄 알았어 💍',
    successBody: '앞으로 잘해줄게. 받아줘서 고마워.',
    successHint: '',
    interaction: { type: 'runaway-no' },
    tags: ['classic', 'runaway-button', 'day-001']
  }
];
